project_2_labyrinth
HromBromIod/Tinkoff_Java pull request #11
Opened 2023-11-05 19:45 UTC by HromBromIod

2023-11-24 12:59 UTC, dmskorikov requested changes

2023-11-30 19:15 UTC, HromBromIod commented
При вызове конструктора в конструкторе, вызов должен быть самой первой операцией. Если так сделать, фактически лабиринт будет иметь максимальные размеры, но логически ограничен случайно заданными значениями.

2023-12-02 14:59 UTC, dmskorikov commented
> При вызове конструктора в конструкторе, вызов должен быть самой первой операцией. Если так сделать, фактически лабиринт будет иметь максимальные размеры, но логически ограничен случайно заданными значениями.

Да, точно. Тогда нужно сделать статический метод, который будет вычислять рандомные ширину и высоту и затем создавать лабиринт с этими значениями через конструктор `public Labyrinth(int n, int m)`

2023-12-02 15:16 UTC, dmskorikov requested changes
при разработке интерфейса класса нужно задумываться об удобстве его использования. У тебя есть несколько лишних публичных методов, которые я бы скрыл.
Т.е. сейчас у тебя нужно писать так:
```
var labyrinth = new Labyrinth(15, 15);
labyrinth.createLabyrinth();
labyrinth.clearWay();
var route = labyrinth.findTheWay(...)        
```

а это можно упростить до:
```
var labyrinth = new Labyrinth(15, 15);
var route = labyrinth.findTheWay(...)        
```

2023-12-02 15:16 UTC, dmskorikov commented on src/main/java/edu/project2labyrinth/Labyrinth.java
> +            maze = personMatrix;
лучше копировать всю матрицу, потому что так ты просто копируешь ссылку и у вызывающего появляется возможность менять внутреннее состояние лабиринта в обход задуманного тобой интерфейса

2023-12-02 15:16 UTC, dmskorikov commented on src/main/java/edu/project2labyrinth/Labyrinth.java
> +    public void createLabyrinth() {
Не совсем понятно зачем делать этот метод публичным, а не вызывать его из конструктора `Labyrinth(int n, int m)`. А для конструктора `Labyrinth(Cell[][] personMatrix, int n, int m)` не вызывать

2023-12-02 15:16 UTC, dmskorikov commented on src/main/java/edu/project2labyrinth/Labyrinth.java
> +    public void clearWay(List<Cell> way) {
этот метод тоже можно сделать приватным и вызывать в начале findTheWay

2023-12-08 19:12 UTC, merged