hw3
HromBromIod/Tinkoff_Java pull request #6
Opened 2023-10-26 21:28 UTC by HromBromIod

2023-11-03 11:22 UTC, dmskorikov requested changes

2023-11-03 11:22 UTC, dmskorikov commented on src/main/java/edu/hw3/Task2/Clusterizator3000.java
> +            if (c == ')' && c != st.peek()) {
Разве в стеке могут храниться закрывающие скобки? Просто лишнее условие путает и может приводить к ошибкам

2023-11-03 11:22 UTC, dmskorikov commented on src/main/java/edu/hw3/Task1/Task1.java
> +    private Task1() {
Понятно что приватный конструктор нужен, чтобы нельзя было создать объект этого класса. Но этим не нужно злоупотреблять, а писать только там где требуется. Для классов с main и для тестовых классов это не надо писать, так как это "захламляет" код и его сложнее читать

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task2Test.java
> +        boolean actual = clusterize("()()()").equals(new ArrayList<>(Arrays.asList("()", "()", "()")));
Если переделать возвращаемый тип clusterize на List<String>, то можно будет упростить создание списков с `new ArrayList<>(Arrays.asList(...))` на `Arrays.asList(...)` или `List.of(...)`

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task3Test.java
> +            freqDict(new ArrayList<>(Arrays.asList(1, 2, 3, 4, 2, 3, 1, 1, 1))).equals(new HashMap<>() {{
Тут необязательно создавать ArrayList

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task5Test.java
> +        String[] metallica = new String[] {"James Hatfield", "Lars Urlich", " Kirk Hammet", "Robert", "   "};
За metallica зачет!

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task5Test.java
> +            new Person(metallica[1].trim(), sortType), new Person(metallica[3].trim(), sortType),
Тут как раз и видно, что неудобно пользоваться классом Person, потому что везде дублируется sortType

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task5Test.java
> +                actual = false;
можно сделать break и убрать `&& actual` из условия цикла

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task6Test.java
> +        ThisMarket market = new ThisMarket();
Тип переменной должен быть интерфейсом - Market

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task6Test.java
> +                actual = false;
Не хватает break, так как если мы уже выяснили, что все сломалось, то нет смысла дальше итерироваться

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task8Test.java
> +        BackwardIterator<?> iterator = new BackwardIterator<>(list);
А почему явно не указан тип BackwardIterator<Integer> ?

2023-11-03 11:22 UTC, dmskorikov commented on src/test/java/edu/hw3/Task8Test.java
> +                actual = false;
Не хватает break

2023-11-03 21:27 UTC, HromBromIod commented
В 3 задаче не уверен, как я через Generic сделал и возвращаю типизированный Map

2023-11-12 10:54 UTC, dmskorikov requested changes

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task2/Clusterizator3000.java
> +                return result;
Так как тут мы имеем дело с "кривыми" входными данными, то лучше вместо возврата пустой строки бросать подходящее исключение. В данном случае - IllegalArgumentException

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task2/Clusterizator3000.java
> +            if (str.equalsIgnoreCase("")) {
вместо сравнения с пустой строкой лучше использовать isEmpty()

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task2/Clusterizator3000.java
> +        for (iterator = 1; !st.isEmpty() && iterator < string.length(); ++iterator) {
Кажется, что текущий алгоритм без ошибок кластеризует такую строку: "())("
Мы же в стек должны класть только открывающие скобки

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task2/Clusterizator3000.java
> +            return result;
Тут тоже лучше бросать исключение IllegalArgumentException
Но вообще эту проверку можно убрать и вместо нее сделать более общую проверку по ходу выполнения кластеризации - если стек пустой и текущий символ закрывающая скобка, то значит у нас "неправильная" строка

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task3/MyGenericForFrecDict.java
> +    public Map<T, Integer> freqDict(List<T> list) {
Да, про типизацию Map я это и имел в виду 👍 

Так как метод не обращается к полям класса, то его нужно сделать статическим. И тогда не нужно типизировать сам класс

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task3/MyGenericForFrecDict.java
> +    public MyGenericForFrecDict() {
Непонятно зачем нам пустой конструктор. Ниже написал, что метод freqDict нужно сделать статическим. Поэтому нам вообще не придется создавать объекты этого класса

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task5/Person.java
> +    private final String name;
В прошлый раз все правильно было с firstName и secondName, а вот sortType нужно убрать
Можно реализовать этот класс через `record(String firstName, String secondName)` и каким-то статическим методом, который создает объект этого класса из одной строки, содержащей имя и фамилию

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task5/Task5.java
> +        Comparator<Person> comparator = (o1, o2) -> {
Компаратор лучше вынести или в отдельный класс или в метод, который будет возвращать эту лямбду. Это упростит код

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task5/Task5.java
> +                newListOfContacts.add(new Person(name, sortType));
Вот тут как раз должен быть метод, который из name формирует Person. 
sortType тут не нужен, он требуется только для сортировки после получения списка Person

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task5/Task5.java
> +        newListOfContacts.sort(comparator);
а вот тут можно сделать анализ sortType и сортировать в прямом порядке или в обратном. Чтобы не писать новый компаратор для обратной сортировки нужно использовать Comparator.reversed()

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task6/ThisMarket.java
> +    private final PriorityQueue<Stock> que;
Поле лучше переименовать в более подходящее. Это же коллекция из Stock - можно назвать stocks

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task6/ThisMarket.java
> +        que = new PriorityQueue<>();
Так как инициализация que не зависит от параметров конструктора, то нужно ее делать "по месту" - там где мы объявляем поле: `private final PriorityQueue<Stock> que = new PriorityQueue<>();`
А так как пустые публичные конструкторы не имеют смысла, то конструктор нужно удалить

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task8/BackwardIterator.java
> +            throw new NullPointerException();
Непонятно почему тут мы бросаем NullPointerException, нужно ведь NoSuchElementException

2023-11-12 10:54 UTC, dmskorikov commented on src/main/java/edu/hw3/Task8/BackwardIterator.java
> +        T[] elements = (T[]) new Object[collection.size()];
Подскажу, что можно вместо `private final Collection<T> collection;` хранить типизированный список: 
`private final List<T> collection;` который инициализировать в конструкторе: `this.collection = collect.stream().toList();`

Так мы только 1 раз создадим копию, а не будем это делать каждый раз

2023-11-12 10:54 UTC, dmskorikov commented on src/test/java/edu/hw3/Task1Test.java
> +        "Did you know who I am?, Wrw blf pmld dsl R zn?",
Нужно ее добавить тесты  с цифрами и русскими буквами - они не должны шифроваться

2023-11-12 10:54 UTC, dmskorikov commented on src/test/java/edu/hw3/Task2Test.java
> +public class Task2Test {
Так как у нас будет бросаться исключение IllegalArgumentException, то нужно переписать тесты с "неправильными" строками на ожидание этого исключения. А также добавить еще пару "неправильных" строк.
Например такую: `(()))(`

2023-11-12 10:54 UTC, dmskorikov commented on src/test/java/edu/hw3/Task5Test.java
> +        boolean expected = true;
Эта переменная же нигде не меняется, поэтому ее можно удалить и вместо assertEquals писать `assertTrue`

2023-11-17 20:51 UTC, merged